# Rede 1
pc0[0]="A"
pc1[0]="A"

# Rede r1 e r2
r1[0]="B"
r1[1]="C"
r1[bridged]="true"
r2[0]="A"
r2[1]="B"

# Rede 2
pc4[0]="C"
pc5[0]="C"

# Rede 3
pc2[0]="D"
pc3[0]="D"

# Rede R1 e R3
r1[2]="E"
r3[0]="D"
r3[1]="E"